import Head from 'next/head';
import { Button } from 'antd';
import sheets from '../services/sheets';

export async function getStaticProps() {
  const [response] = await sheets.loadRecords();
  return {
    props: {
      data: response.body,
    },
  };
}

export default function Home(props) {
  const { data } = props;
  return (
    <div>
      <Head>
        <title>Women.krd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button type="primary" size="large">This is a button</Button>
      <pre>{JSON.stringify(data)}</pre>
    </div>
  );
}
