import { useContext } from 'react';
import Head from 'next/head';
import { Row, Col } from 'antd';

import Filters from '../components/Filters';
import DataContext from '../helpers/DataContext';

function Report() {
  const data = useContext(DataContext);
  console.log(data);
  return (
    <div>
      <Head>
        <title>Women.krd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Row>
        <Col span={24}>
          <Filters />

        </Col>
        <Col span={24}>
          <p>{JSON.stringify(data.records)}</p>
          <hr />
          <p>{JSON.stringify(data.types)}</p>

        </Col>
      </Row>

    </div>
  );
}

export default Report;
